tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, TaskDeleteView, TaskDetailView
from tasks.views import TaskListView
from tasks.views import TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("<int:id>/", TaskDetailView, name="task_detail"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("projects/", include("projects.urls")),
    path("tasks/", include("tasks.urls")),
    path("admin/", admin.site.urls),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("accounts/", include("accounts.urls")),
]

tasks/models.py
from django.db import models
from projects.models import USER_MODEL
from projects.models import Project

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="tasks"
    )
    assignee = models.ForeignKey(
        USER_MODEL, models.SET_NULL, null=True, related_name="tasks"
    )

    def __str__(self):
        return self.name


class Note(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    tasks = models.ForeignKey(
        "Task", on_delete=models.CASCADE, related_name="notes"
    )

tasks/forms.py
from django.forms import ModelForm

from tasks.models import Note


class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ["description"]

tasks/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from tasks.forms import NoteForm

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=(self.object.project.id,))


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")


def TaskDetailView(request, id):
    task = Task.objects.get(id=id)
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            form.instance.tasks = task
            form.save()
            return redirect("task_detail", id)
    else:
        notes = task.notes.all
        form = NoteForm()
        context = {
            "form": form,
            "notes": notes,
            "task": task,
        }
        return render(request, "tasks/detail.html", context)


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/delete.html"
    success_url = reverse_lazy("show_my_tasks")

tasks/templates/tasks/create.html
{% load static %}
<!doctype html>
<html>
    <head>
        <title>Create a new task</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <header>
            <nav class="navbar-nav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'show_my_tasks' %}">My Tasks</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'list_projects' %}">My Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main class="text-center">
            <div class="card">
                <h1 class="card-header">Create a new task</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-lg">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

tasks/templates/tasks/delete.html
{% load static %}
<!doctype html>
<html>
    <head>
        <title>Delete task</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <header>
            <nav class="navbar-nav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'show_my_tasks' %}">My Tasks</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'list_projects' %}">My Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main class="text-center">
            <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ task.name }}"?</p>
                {{ form.as_p }}
                <div class="control">
                  <button type="submit" class="btn btn-danger">Delete</button>
                </div>
              </form>
        </main>
    </body>
</html>

tasks/templates/tasks/detail.html
{% load static %}
<!doctype html>
<html>
    <head>
        <title>Create a new task</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <header>
            <nav class="navbar-nav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'show_my_tasks' %}">My Tasks</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'list_projects' %}">My Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main class="text-center">
            <div>
                <h1>{{ task.name }}</h1>
                <p>{{ task.start_date }} to {{ task.due_date }}</p>
            </div>
            <div>
                <h1>Notes</h1>
                {% for note in notes %}
                <h3>{{ note.date }}</h3>
                <p>{{ note.description }}</p>
                <br></br>
                {% empty %}
                <p>You have not created any notes for this task. Create a note below!</p>
                {% endfor %}
            </div>
            <div>
                <h3>Enter your notes here</h3>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                  <div>
                      <button type="submit" class="btn btn-primary btn-lg">Create</button>
                  </div>
                </form>
            </div>
        </main>
    </body>
</html>

tasks/templates/tasks/list.html
{% load static %}
<html>
    <head>
        <title>My Tasks</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <header>
            <nav class="navbar-nav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'show_my_tasks' %}">My Tasks</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'list_projects' %}">My Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1 class="text-center"> My Tasks</h1>
                {% if task_list %}
                    <table class="table text-center">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Assignee</th>
                                <th>Start date</th>
                                <th>Due date</th>
                                <th>Is completed</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in task_list %}
                                <tr>
                                    <td><a href="{% url 'task_detail' task.id %}">{{ task.name }}</a></td>
                                    <td>{{ task.assignee }}</td>
                                    <td>{{ task.start_date }}</td>
                                    <td>{{ task.due_date }}</td>
                                    {% if task.is_completed %}
                                        <td>Done</td>
                                    {% else %}
                                        <td><form method="post" action="{% url 'complete_task' task.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="is_completed" value="True">
                                            <button type="submit" class="btn btn-primary btn-sm">Complete</button>
                                        </form></td>
                                    {% endif %}
                                    <td><a href="{% url 'task_delete' task.id %}">Delete this task</a><td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>You have no tasks</p>
                {% endif %}
            </div>
        </main>
    </body>
</html>