projects/urls.py
from django.urls import path
from projects.views import ProjectListView
from projects.views import ProjectDetailView
from projects.views import ProjectCreateView

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:id>/", ProjectDetailView, name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, TaskDeleteView, TaskDetailView
from tasks.views import TaskListView
from tasks.views import TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("<int:id>/", TaskDetailView, name="task_detail"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("projects/", include("projects.urls")),
    path("tasks/", include("tasks.urls")),
    path("admin/", admin.site.urls),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("accounts/", include("accounts.urls")),
]

projects/models.py
from django.db import models
from django.conf import settings
from datetime import datetime, timedelta
from django.utils import timezone

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

    def is_finished(self):
        for task in self.tasks.all():
            if task.is_completed is False:
                return False
        return True


class Message(models.Model):
    creator = models.ForeignKey(
        USER_MODEL, on_delete=models.PROTECT, related_name="messages"
    )
    project = models.ForeignKey(
        "Project", on_delete=models.CASCADE, related_name="messages"
    )
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


class Poll(models.Model):
    Title = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    def is_open(self):
        if timezone.now() - timedelta(days=1) > self.date:
            return False
        return True

    def winner(self):
        count = max([choice.number_of_votes for choice in self.choices.all()])
        chosen = self.choices.objects.get(number_of_votes=count)
        return chosen

    def already_taken(self):
        list = []
        for choice in self.choices.all():
            for voter in choice.voters:
                list.append(voter)
        if self.request.user in list:
            return True
        return False


class Choice(models.Model):
    name = models.CharField(max_length=200)
    poll = models.ForeignKey(
        "Poll", on_delete=models.CASCADE, related_name="choices"
    )
    number_of_votes = models.IntegerField(default=0)
    voters = models.ManyToManyField(USER_MODEL, related_name="choices")

    def __str__(self):
        return self.name

    def add_vote(self):
        self.number_of_votes += 1

projects/forms.py
from django.forms import ModelForm

from projects.models import Message


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ["content"]

projects/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.shortcuts import redirect, render
from projects.forms import MessageForm

from projects.models import Project
from tasks.models import Task
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime, timedelta
from django.utils import timezone

# Create your views here.
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks_upcoming = []
        tasks_past_due = []
        tasks_due_today = []
        for task in self.request.user.tasks.all():
            if (
                timezone.now() < task.due_date
                and timezone.now() + timedelta(days=1) > task.due_date
            ):
                tasks_due_today.append(task)
            elif timezone.now() > task.due_date:
                tasks_past_due.append(task)
            elif timezone.now() + timedelta(days=7) > task.due_date:
                tasks_upcoming.append(task)
        context["tasks_upcoming"] = tasks_upcoming
        context["tasks_past_due"] = tasks_past_due
        context["tasks_due_today"] = tasks_due_today
        return context


def ProjectDetailView(request, id):
    if request.user.is_authenticated is False:
        return redirect("login")
    project = Project.objects.get(id=id)
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            form.instance.project = project
            form.instance.creator = request.user
            form.save()
            return redirect("show_project", id)
    form = MessageForm()
    messages = project.messages.all()
    return render(
        request,
        "projects/detail.html",
        {"form": form, "messages": messages, "project": project},
    )


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=(self.object.id,))

projects/templates/projects/create.html
{% load static %}
<!doctype html>
<html>
    <head>
        <title>Create Project</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <header>
            <nav class="navbar-nav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'show_my_tasks' %}">My Tasks</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'list_projects' %}">My Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main class="text-center">
            <div class="card">
                <h1 class="card-header">Create a new project</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-lg">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

projects/templates/projects/detail.html
{% load markdownify %}
{% load static %}
<!doctype html>
<html>
    <head>
        <title>Project Detail</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <header>
            <nav class="navbar-nav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'show_my_tasks' %}">My Tasks</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'list_projects' %}">My Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main class="text-center">
            <div>
                <h1>{{ project.name }}</h1>
                <p>{{ project.description|markdownify }}</p>
                <h2>Tasks</h2>
                <p><a href="{% url 'create_task' %}">Create a new task</a></p>
                {% if project.tasks.all %}
                    <table class="table text-center">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Assignee</th>
                                <th>Start date</th>
                                <th>Due date</th>
                                <th>Is completed</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in project.tasks.all %}
                                <tr>
                                    <td>{{ task.name }}</td>
                                    <td>{{ task.assignee }}</td>
                                    <td>{{ task.start_date }}</td>
                                    <td>{{ task.due_date }}</td>
                                    {% if task.is_completed %}
                                        <td>Yes</td>
                                    {% else %}
                                        <td>No</td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>This project has no tasks</p>
                {% endif %}
            </div>
            <div>
                <h1>Collab Space</h1>
                <p>Write messages to project members here!</p>
                {% for message in messages %}
                <p>{{ message.creator }} on {{ message.date }}</p>
                <p>{{ message.content }}</p>
                {% empty %}
                <p>No messages yet. Write a message to the group down below!</p>
                {% endfor %}
            </div>
            <div>
                <h2>Create message here</h2>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div>
                        <button type="submit" class="btn btn-primary btn-lg">Post</button>
                    </div>
                </form>
            </div>
        </main>
    </body>
</html>

projects/templates/projects/list.html
{% load static %}
<!doctype html>
<html>
    <head>
        <title>Projects</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <header>
            <nav class="navbar-nav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'show_my_tasks' %}">My Tasks</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'list_projects' %}">My Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main class="text-center">
            <h1>{{ user }}'s Project Manager</h1>
            <br></br>
            <div class="card">
                <h2 class="card-header">Past due tasks</h2>
                {% for task in tasks_past_due %}
                <p><a href="{% url 'task_detail' task.id %}">{{ task.name }}</a></p>
                {% empty %}
                <p>Congratulations! No past due tasks</p>
                {% endfor %}
            </div>
            <div class="card">
                <h2 class="card-header">Tasks due in the next 24 hours</h2>
                {% for task in tasks_due_today %}
                <p><a href="{% url 'task_detail' task.id %}">{{ task.name }}</a></p>
                {% empty %}
                <p>No tasks due today!</p>
                {% endfor %}
            </div>
            <div class="card">
                <h2 class="card-header">Upcoming Tasks due in the next week</h2>
                {% for task in tasks_upcoming %}
                <p><a href="{% url 'task_detail' task.id %}">{{ task.name }}</a></p>
                {% empty %}
                <p>No upcoming tasks</p>
                {% endfor %}
            </div>
            <div>
                <h1>My Projects</h1>
                <p><a href="{% url 'create_project' %}">Create a new project</a></p>
                {% if project_list %}
                    <table class="table text-center">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Number of tasks</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project in project_list %}
                                <tr>
                                    <td><a href="{% url 'show_project' project.id %}">{{ project.name }}</a></td>
                                    <td>{{ project.tasks.all|length }}</td>
                                    {% if project.is_finished %}
                                    <td>project is complete</td>
                                    {% else %}
                                    <td>project in progress</td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>You are not assigned to any projects</p>
                {% endif %}
            </div>
        </main>
    </body>
</html>